name: RTPZone
version: '1.0'
main: dev.anshxx.rtpzone.Main
api-version: '1.20'
description: Enhance multiplayer experience with random teleportation within specified regions.
authors:
  - anshxx
depend:
  - WorldGuard
  - WorldEdit
